apiVersion: v1
kind: Service
metadata:
  name: front
  labels:
    app: Front
spec:
  type: NodePort
  selector:
    app: lab3-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31111