apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deplt
  labels:
    app: fronted
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fronted
  template:
    metadata:
      labels:
        app: fronted
    spec:
      containers:
      - name: frontned-container
        image: ifilyaninitmo/itdt-contained-frontend:master
        resources: 
          limits:
            memory: "512M"
            cpu: ".5"
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_USERNAME
          value: Russkin_Vadim
        - name: REACT_APP_COMPANY_NAME
          value: ITMO